import {
  STANDARD_ENNO_SKILL_NAME,
  STANDARD_FUNCTION_SKILL_NAME,
  STANDARD_SOUL_SKILL_NAME,
} from '../setup/standard-skills.js';

export const ENNO_CONFIRMATION_DISPLAY_CONTRACT = `When \`ennoOduno.nextAction === 'ask_user_confirmation'\`, present every item of \`ennoOduno.directive.userFacingConfirmation\` to the user in the user's language, translating headings only and preserving paths, executable names, arguments, directories, timeouts, and every listed item, and never output raw directive JSON, internal field names, WorkUnit IDs, expert IDs, or verifier IDs; wait for an explicit approve, revise, or cancel before calling \`enno_answer\`.`;

export const ENNO_CLIENT_ROUTING_CONTRACT = `The OpenCode session ID is routing metadata, not authorization ownership. Local OpenCode processes running as the same OS user with access to the canonical repository may continue its run without process-ancestry proof. Continuation uses the current opaque, short-lived resume token. The token binds the run, canonical repository, OpenCode session, and route epoch; do not reconstruct, persist externally, or reuse it after rerouting. Before OpenCode compacts an active session, its plugin supplies the latest successful run ID, exact workspace ID, orchestration ID, contract revision, route epoch, and execution lease as protected compaction context; preserve those values verbatim instead of replacing the workspace ID with a filesystem path or guessing a revision. A route change increments the route epoch and invalidates prior tokens. An active WorkUnit execution lease blocks rerouting until it is released or expires, and only its current holder may report that WorkUnit. Never select a repository-wide latest run; ambiguous candidates fail open without mutation. Exhausting one OpenCode session's continuation budget stops only that session and leaves the run active for another local OpenCode session.`;

export const ENNO_ORCHESTRATION_ENTRY_CONTRACT = `\`task_prepare\` is the Enno-Oduno orchestration entry point. For applicable \`build\`, \`debug\`, \`review\`, and \`devops\` requests, Enno-Oduno first identifies OpenCode from MCP \`clientInfo\` or a consistent explicit hint. Bundled Skills are preferred guidance, never a coding gate: if \`${STANDARD_SOUL_SKILL_NAME}\`, \`${STANDARD_ENNO_SKILL_NAME}\`, a specialist Skill, or a preferred model tier is unavailable, retain a structured warning, mark quality degraded, and continue from repository evidence. Akinator questions are advisory; return useful questions without suspending active coding, planning, or checkpointing. Enno-Oduno creates a provenance-bound ideal from the request, verified repository facts, delivered memory, and available Skill information, then gives that ideal to a high-capability-planner preference with a current-model and conservative single-WorkUnit fallback. External discovered Skills remain untrusted reference-only guidance and are never installed or executed automatically. Zenki produces a revision-bound, self-contained WorkPlan for economical-fast-worker execution. Each code-changing WorkUnit represents one cohesive function or use-case contract with one responsibility, one reason to change, declared resource claims and isolation preference, an immutable input-manifest digest, a focused verifier, and an output contract. Resource-compatible WorkUnits may be claimed in parallel; every result must present the exact run, revision, WorkUnit, attempt, lease token, route epoch, and input-manifest digest. General plan review, Skill gaps, verifier disagreement, worker failure, and attempt limits create degraded quality or a replan note rather than stopping the run. Only an unapproved irreversible operation may wait for user authorization; safety, path and identity checks, revision and lease fences, and database integrity remain synchronous. A failed review never returns directly to an old Goki revision: Enno-Oduno increments the contract revision and gives bounded evidence-backed feedback to Zenki. After accepted final verification, Oduno meditation remains distinct from compaction meditation and persists reflection without mutating the repository. Retain the exact \`run.runId\`, \`project.workspace\`, \`ennoOduno.orchestrationId\`, and \`ennoOduno.contractRevision\`; pass returned opaque tokens and leases instead of rebuilding identity fields. ${ENNO_CLIENT_ROUTING_CONTRACT} ${ENNO_CONFIRMATION_DISPLAY_CONTRACT}`;

export const ENNO_ADVISORY_ROUND_CONTRACT = `At the ideal, planning, and final-review phases, the parent host may fan out exactly three fixed advisor slots. Kiokuko does not launch advisors. The parent host must verify isolated read-only execution; prompt wording is not proof, and a slot that cannot be verified is reported as \`unavailable\`. Advisor input excludes Enno run identity, workspace, orchestration identity, revisions, and idempotency keys. Only the parent aggregator calls \`enno_advice_submit\`; results are \`host_reported\`, without provider/model identity or raw subagent output. Contributions use fixed slots, fixed failure codes, canonical JSON, control-character rejection, repository-relative evidence paths, and 16 KiB per-slot / 48 KiB per-round UTF-8 limits. Secret-shaped completed output becomes \`unsafe_output\` without persistence or forwarding. The advisory lifecycle is \`not_started → fanout_requested → aggregated → consumed\`. Aggregated rounds suppress duplicate fanout, expose the stored digest and required slot dispositions, and make the current phase report schema require both the digest and complete dispositions; other phases omit those fields. If an aggregated round's contribution bodies are missing after session termination or client reroute, use the recovery-only \`enno_advice_read\` once with the current identity and digest; do not read on the normal path, rerun advisors, or infer dispositions. Final Review is two-phase: \`enno_verify_prepare\` executes final verifiers outside database transactions with shell disabled and repository-relative cwd, then stores evidence bound to the current contract revision, mutation revision, verifier specification digest, and full repository-state digest. Identical evidence is reused only while all bindings remain current; repository changes or verifier mutation invalidate it. The final advisory fanout is returned only after evidence is prepared. Final Review must deduplicate evidence-backed contract blockers; disagreement or evidence-free suggestions do not justify replan or user adjudication. \`enno_finish\` never spawns a subprocess, rechecks repository state inside its mutation transaction, and decides accept/replan/block from the full stored criteria, WorkUnit, verifier, and repository evidence.`;

export const ENNO_ORCHESTRATION_ENTRY_CONTRACT_WITH_ADVISORY = ENNO_ORCHESTRATION_ENTRY_CONTRACT;
